export const SAVE_EVENT = "SAVE_EVENT";
export const SAVE_EVENT_PRACTIONNER_FILTER = "SAVE_EVENT_PRACTIONNER_FILTER";
export const LOADING_EVENT_PRACTIONNER_FILTER_START= "LOADING_EVENT_PRACTIONNER_FILTER_START";
