export const SAVE_EVENT = "SAVE_EVENT";
<<<<<<< HEAD
export const SAVE_EVENT_PRACTIONNER_FILTER = "SAVE_EVENT_PRACTIONNER_FILTER";
=======
export const SAVE_EVENT_PRACTIONNER_FILTER = "SAVE_EVENT_PRACTIONNER_FILTER";
>>>>>>> 44c74b29ceaf6d946783a486df51db0240c0749e
