export const FETCH_CIVILITIES_REQUEST = 'FETCH_CIVILITIES_REQUEST';
export const FETCH_CIVILITIES_SUCCESS = 'FETCH_CIVILITIES_SUCCESS';
export const FETCH_CIVILITIES_FAILURE = 'FETCH_CIVILITIES_FAILURE';