export const DATA_TABLE_PRATICIEN_COLONNE = ["Civilité", "Profession", "Nom", "Prenom", "Initials", "Actif", "Date de fin d'activité", "Est chirurgien", "Le groupe", "Lieu", "Prix defaut", "Actions"]
export const DATA_TABLE_PATIENT_COLONNE = ["Civilité", "Nom", "Prénom", "Date de naissance", "Téléphone", "Email", "Mot de Passe", "Initials", "Photo", "Actif", "Droits", "Actions"]
export const DATA_TABLE_LIEU_COLONNE = ["Label", "Ville", "Région", "Code Postal", "Réference", "Initials", "Coordonées geographique", "Actif", "Actions"]
export const DATA_TABLE_MOTIF_COLONNE = ["Label", "Nom", "Temps par défaut", "Couleur Motif", "Reference", "Actif", "Actions"]
export const DATA_TABLE_SPECIALITE_COLONNE = ["Label", "Nom", "Reference", "Actif", "Alerte web", "Alerte secretaire", "Actions"]
export const DATA_TABLE_USERS_COLONNE = ["Civilité", "Nom", "Prénom", "Date de naissance", "Téléphone", "Email", "Mot de Passe", "Initials", "Photo", "Actif", "Droits", "Actions"]
export const DATA_TABLE_GROUPE_COLONNE = ["Nom du groupe", "Description", "Actions"]