export const EMAIL = "email"
export const TEXT = "text"
export const RADIO = "radio"
export const FILE = "file"
export const SELECT = "select"
export const DATE = "date"
export const TEXT_AREA = "text-area"
