export const FETCH_PRATICIENS_REQUEST = "FETCH_PRATICIENS_REQUEST";

export const FETCH_PRATICIENS_SUCCESS = "FETCH_PRATICIENS_SUCCESS";

export const FETCH_PRATICIENS_FAILURE = "FETCH_PRATICIENS_FAILURE";
/* 
export const FETCH_CIVILITIES_REQUEST = "FETCH_CIVILITIES_REQUEST";

export const FETCH_CIVILITIES_SUCCESS = "FETCH_CIVILITIES_SUCCESS";

export const FETCH_CIVILITIES_FAILURE = "FETCH_CIVILITIES_FAILURE"; */