const rows = [
    {
      'id': 1,
      "Actions": "action1",
      "id Module externe": "uuid1",
      "population": 123,
      "Abréviation": "ab1",
      "Libéllé": "libellé1",
      "Libéllé patient": "libellé patient 1",
      "Temps du rdv par defaut": 10,
      "Montant de l'acte": 100,
      "Nombre de personnes": 5,
      "Accessible par internet": true,
      "Ordre pour internet": 1,
      "Temps decalage Prise de RDV": 30,
      "Proposer un rdv après": 20,
      "Proposer un rdv jusqu'à": 40,
      "Motif par defaut": "motif1",
      "Couleur": "#ff0000",
      "Protocole": "protocole1",
      "Controle Prise de RDV": true,
      "Age minimum (inclus)": 18,
      "Age maximum (inclus)": 65,
      "Motif anonyme": "anonyme1"
    },
    {
      'id': 2,
      "Actions": "action2",
      "id Module externe": "uuid2",
      "population": 456,
      "Abréviation": "ab2",
      "Libéllé": "libellé2",
      "Libéllé patient": "libellé patient 2",
      "Temps du rdv par defaut": 20,
      "Montant de l'acte": 200,
      "Nombre de personnes": 10,
      "Accessible par internet": false,
      "Ordre pour internet": 2,
      "Temps decalage Prise de RDV": 60,
      "Proposer un rdv après": 40,
      "Proposer un rdv jusqu'à": 80,
      "Motif par defaut": "motif2",
      "Couleur": "#00ff00",
      "Protocole": "protocole2",
      "Controle Prise de RDV": false,
      "Age minimum (inclus)": 20,
      "Age maximum (inclus)": 70,
      "Motif anonyme": "anonyme2"
    },
    {
        'id': 3,
        "Actions": "action2",
        "id Module externe": "uuid2",
        "population": 456,
        "Abréviation": "ab2",
        "Libéllé": "libellé2",
        "Libéllé patient": "libellé patient 2",
        "Temps du rdv par defaut": 20,
        "Montant de l'acte": 200,
        "Nombre de personnes": 10,
        "Accessible par internet": false,
        "Ordre pour internet": 2,
        "Temps decalage Prise de RDV": 60,
        "Proposer un rdv après": 40,
        "Proposer un rdv jusqu'à": 80,
        "Motif par defaut": "motif2",
        "Couleur": "#00ff00",
        "Protocole": "protocole2",
        "Controle Prise de RDV": false,
        "Age minimum (inclus)": 20,
        "Age maximum (inclus)": 70,
        "Motif anonyme": "anonyme2"
      },
      {
        'id': 4,
        "Actions": "action2",
        "id Module externe": "uuid2",
        "population": 456,
        "Abréviation": "ab2",
        "Libéllé": "libellé2",
        "Libéllé patient": "libellé patient 2",
        "Temps du rdv par defaut": 20,
        "Montant de l'acte": 200,
        "Nombre de personnes": 10,
        "Accessible par internet": false,
        "Ordre pour internet": 2,
        "Temps decalage Prise de RDV": 60,
        "Proposer un rdv après": 40,
        "Proposer un rdv jusqu'à": 80,
        "Motif par defaut": "motif2",
        "Couleur": "#00ff00",
        "Protocole": "protocole2",
        "Controle Prise de RDV": false,
        "Age minimum (inclus)": 20,
        "Age maximum (inclus)": 70,
        "Motif anonyme": "anonyme2"
      },
      {
        'id': 5,
        "Actions": "action2",
        "id Module externe": "uuid2",
        "population": 456,
        "Abréviation": "ab2",
        "Libéllé": "libellé2",
        "Libéllé patient": "libellé patient 2",
        "Temps du rdv par defaut": 20,
        "Montant de l'acte": 200,
        "Nombre de personnes": 10,
        "Accessible par internet": false,
        "Ordre pour internet": 2,
        "Temps decalage Prise de RDV": 60,
        "Proposer un rdv après": 40,
        "Proposer un rdv jusqu'à": 80,
        "Motif par defaut": "motif2",
        "Couleur": "#00ff00",
        "Protocole": "protocole2",
        "Controle Prise de RDV": false,
        "Age minimum (inclus)": 20,
        "Age maximum (inclus)": 70,
        "Motif anonyme": "anonyme2"
      },
      {
        'id': 6,
        "Actions": "action2",
        "id Module externe": "uuid2",
        "population": 456,
        "Abréviation": "ab2",
        "Libéllé": "libellé2",
        "Libéllé patient": "libellé patient 2",
        "Temps du rdv par defaut": 20,
        "Montant de l'acte": 200,
        "Nombre de personnes": 10,
        "Accessible par internet": false,
        "Ordre pour internet": 2,
        "Temps decalage Prise de RDV": 60,
        "Proposer un rdv après": 40,
        "Proposer un rdv jusqu'à": 80,
        "Motif par defaut": "motif2",
        "Couleur": "#00ff00",
        "Protocole": "protocole2",
        "Controle Prise de RDV": false,
        "Age minimum (inclus)": 20,
        "Age maximum (inclus)": 70,
        "Motif anonyme": "anonyme2"
      },
  ];
  export default rows;