export const FETCH_PROFESSION_REQUEST = 'FETCH_PROFESSION_REQUEST';
export const FETCH_PROFESSION_SUCCESS = 'FETCH_PROFESSION_SUCCESS';
export const FETCH_PROFESSION_FAILURE = 'FETCH_PROFESSION_FAILURE';